// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjoL28JuYC3ptTFZJWpLt0toTdvoY1OEs',
    appId: '1:170447288358:web:3cb884d00205c19f130ee7',
    messagingSenderId: '170447288358',
    projectId: 'talent-folio-ed6c1',
    authDomain: 'talent-folio-ed6c1.firebaseapp.com',
    storageBucket: 'talent-folio-ed6c1.firebasestorage.app',
    measurementId: 'G-YT3BF62KZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFTA-juuVPpdkER2syq-Ufys7CKkyZZgg',
    appId: '1:170447288358:android:58fc1c2ba705387b130ee7',
    messagingSenderId: '170447288358',
    projectId: 'talent-folio-ed6c1',
    storageBucket: 'talent-folio-ed6c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgkzjPowwWcCz_ImK9c3gtmemg5yIm80I',
    appId: '1:170447288358:ios:be9c7cf262bb5ea3130ee7',
    messagingSenderId: '170447288358',
    projectId: 'talent-folio-ed6c1',
    storageBucket: 'talent-folio-ed6c1.firebasestorage.app',
    iosBundleId: 'com.example.talentfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJCb-3GmIlJxXA_kWBQEZ43Tb2xK9m0Q8',
    appId: '1:63828931693:ios:c11a7ec60905648807fb64',
    messagingSenderId: '63828931693',
    projectId: 'talent-folio-875cc',
    storageBucket: 'talent-folio-875cc.firebasestorage.app',
    iosBundleId: 'com.example.talentfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWTxbBJVCRSpHpq3RW9Lb4VLHn6KdHrnA',
    appId: '1:63828931693:web:6af8b074664435c907fb64',
    messagingSenderId: '63828931693',
    projectId: 'talent-folio-875cc',
    authDomain: 'talent-folio-875cc.firebaseapp.com',
    storageBucket: 'talent-folio-875cc.firebasestorage.app',
    measurementId: 'G-M6HW6WMLM4',
  );
}